version: '3'

services:
  db:
      image: mysql
      environment:
          - MYSQL_DATABASE=keycloak
          - MYSQL_USER=keycloak
          - MYSQL_PASSWORD=password
          - MYSQL_ROOT_PASSWORD=root_password
      ports:
          - 3309:3306  # Port diubah agar sesuai dengan konfigurasi default MySQL

  phpmyadmin: 
      image: phpmyadmin/phpmyadmin
      environment:
          - PMA_HOST=db
          - PMA_USER=root
          - PMA_PASSWORD=root_password
      ports:
          - 8081:80  # Mengekspos phpMyAdmin pada port 8081

  keycloak:
      image: quay.io/keycloak/keycloak:25.0.5
      environment:
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
          - DB_VENDOR=mysql
          - DB_ADDR=db
          - DB_PORT=3306
      links:
          - db:db
      ports:
          - 8180:8080  # Ganti port 8080 menjadi 8180
          - 9999:9990
          - 443:8443
      volumes:
          - ./data:/data
      command: start-dev
      depends_on:
        - db
